### ISSUE TITLE
Arquivamento do repositório

### ISSUE THREAD

**Issue by vgeorge** [mapascoletivos/yby-legacy#117]
Oi pessoal, em algum momento passamos a utilizar os repositórios [yby](https://github.com/mapascoletivos/yby) e [yby-client](https://github.com/mapascoletivos/yby-client), e o código deste repositório ficou obsoleto. Adicionei uma nota ao README avisando isso. Para eviter confusão, gostaria de renomear este repositório para `legacy` ou `mc-legacy` e [arquivá-lo](https://help.github.com/articles/about-archiving-repositories/). De acordo?

cc @gufalei @julianamori

**Comment by julianamori** [comment]
Oi @vgeorge, vi o link sobre o que significa arquivar o repositório, mas confesso que não entendi em termos práticos o que significa este arquivamento para o projeto que está no ar. Yby e yby-client são os repósitórios atuais do site?

**Comment by vgeorge** [comment]
Sim, eu não lembro exatamente porque se deu a separação, mas pelo que parece começamos o trabalho aqui e depois separamos em `yby` e `yby-client`. Todas as atualizações posteriores ao desenvolvimento inicial foram feitas nestes repositórios. 

Se arquivamos este repositório ele entrará em modo somente leitura. Além do aviso de que ele está arquivado, não será mais permitido enviar código ou abrir issues. Acho que faz sentido porque não vamos mais trabalho com o código daqui e seria bom que o histórico permanecesse público.

**Comment by julianamori** [comment]
ah entendi @vgeorge, então pra mim tb faz sentido arquivá-lo.

**Comment by vgeorge** [comment]
Vou arquivar agora. Repositório atuais são [webapp](https://github.com/mapascoletivos/webapp) e [api-service](https://github.com/mapascoletivos/api-service).
